# Generated by Django 3.2.9 on 2021-12-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_host'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
