# Generated by Django 3.2.9 on 2021-12-09 08:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0004_courses_exams_food_grades_locations_locationtype_userscourses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Exams',
            new_name='Exam',
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='UsersCourses',
            new_name='UserCourse',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='type_id',
            new_name='type',
        ),
    ]
