# Generated by Django 3.2.9 on 2021-12-09 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_auto_20211209_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='long',
            field=models.FloatField(null=True),
        ),
    ]
