# Generated by Django 3.2.9 on 2021-12-09 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0010_auto_20211209_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationtype',
            options={},
        ),
    ]
