# Generated by Django 3.2.9 on 2021-12-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0012_auto_20211209_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='img_link',
            field=models.TextField(default='#', null=True),
        ),
    ]
