# Generated by Django 3.2.9 on 2021-12-09 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0013_auto_20211209_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='chat_id',
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.TextField(default='course', null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(default='exam', max_length=200),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.TextField(max_length=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='tags',
            field=models.TextField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='tags',
            field=models.TextField(default='location', null=True),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tags', models.TextField(default='#', null=True)),
                ('img_link', models.TextField(default='#', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
